version: "2"
services: 
  my-wpdb: 
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD:  password
  phpadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - my-wpdb:mysql
    ports:
      - "8181:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT_3306_TCP_ADDR: my-wpdb
